[workspace]
resolver = "2"
members = [
  "xtask",
  "crates/lunc",
  "crates/lunc_clifgen",
  "crates/lunc_codegen",
  "crates/lunc_diag",
  "crates/lunc_dsir",
  "crates/lunc_fir",
  "crates/lunc_firgen",
  "crates/lunc_lexer",
  "crates/lunc_parser",
  "crates/lunc_scir",
  "crates/lunc_utils",
  "crates/luntests",
]

[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
lunc_clifgen = { path = "crates/lunc_clifgen" }
lunc_codegen = { path = "crates/lunc_codegen" }
lunc_diag = { path = "crates/lunc_diag" }
lunc_dsir = { path = "crates/lunc_dsir" }
lunc_fir = { path = "crates/lunc_fir" }
lunc_firgen = { path = "crates/lunc_firgen" }
lunc_lexer = { path = "crates/lunc_lexer" }
lunc_parser = { path = "crates/lunc_parser" }
lunc_scir = { path = "crates/lunc_scir" }
lunc_utils = { path = "crates/lunc_utils" }

# other dependencies
thiserror = "2.0.16"
codespan-reporting = "0.12.0"
bytemuck = { version = "1.23.0", features = ["must_cast", "derive"] }
half = "2.6.0"
termcolor = "1.4.1"
serde = { version = "1.0.219", features = ["derive"] }
