[workspace]
resolver = "2"
members = [
  "crates/l2_bytecode",
  "crates/l2_diagnostic",
  "crates/l2_lexer",
  "crates/l2_parser",
  "crates/l2_utils",
  "crates/l2_vm",
  "."
]

[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
l2_bytecode = { path = "crates/l2_bytecode" }
l2_diagnostic = { path = "crates/l2_diagnostic" }
l2_lexer = { path = "crates/l2_lexer" }
l2_parser = { path = "crates/l2_parser" }
l2_utils = { path = "crates/l2_utils" }
l2_vm = { path = "crates/l2_vm" }

# other dependencies
thiserror = "2.0.12"
codespan-reporting = "0.12.0"

[package]
name = "l2"
version.workspace = true
edition = "2024"

[dependencies]
l2_bytecode = { workspace = true }
l2_diagnostic = { workspace = true }
l2_lexer = { workspace = true }
l2_parser = { workspace = true }
l2_utils = { workspace = true }
l2_vm = { workspace = true }

# other dependencies
thiserror = { workspace = true }
codespan-reporting = { workspace = true }
