[workspace]
resolver = "2"
members = [
  "compiler/lunc",
  "compiler/lunc_clifgen",
  "compiler/lunc_codegen",
  "compiler/lunc_diag",
  "compiler/lunc_dsir",
  "compiler/lunc_fir",
  "compiler/lunc_firgen",
  "compiler/lunc_lexer",
  "compiler/lunc_parser",
  "compiler/lunc_scir",
  "compiler/lunc_utils",
  "src/tools/xtask",
  "src/tools/luntests",
]

[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
lunc_clifgen = { path = "compiler/lunc_clifgen" }
lunc_codegen = { path = "compiler/lunc_codegen" }
lunc_diag = { path = "compiler/lunc_diag" }
lunc_dsir = { path = "compiler/lunc_dsir" }
lunc_fir = { path = "compiler/lunc_fir" }
lunc_firgen = { path = "compiler/lunc_firgen" }
lunc_lexer = { path = "compiler/lunc_lexer" }
lunc_parser = { path = "compiler/lunc_parser" }
lunc_scir = { path = "compiler/lunc_scir" }
lunc_utils = { path = "compiler/lunc_utils" }

# other dependencies
thiserror = "2.0.16"
codespan-reporting = "0.12.0"
half = "2.6.0"
termcolor = "1.4.1"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.47", features = ["derive"] }
humantime = "2.3.0"
