[package]
name = "l2_diagnostic"
description = "Diagnostics for l2."
version.workspace = true
edition = "2024"

[dependencies]
l2_utils = { workspace = true }

thiserror = { workspace = true }
codespan-reporting = { workspace = true }
