[package]
name = "lun_codegen"
description = "Code generation of lun."
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
lun_utils = { workspace = true }
lun_bc = { workspace = true }
lun_semack = { workspace = true }
lun_diag = { workspace = true }
