[package]
name = "lunc_firgen"
description = "FIR Generator, SCIR -> FIR"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
lunc_utils = { workspace = true }
lunc_scir = { workspace = true }
lunc_fir = { workspace = true }

# other dependencies
