[package]
name = "l2_parser"
description = "Parser for l2."
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
l2_diagnostic = { workspace = true }
l2_utils = { workspace = true }

thiserror = { workspace = true }
