[package]
name = "lunc_diag"
description = "Diagnostics for Lun."
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
lunc_utils = { workspace = true }

thiserror = { workspace = true }
codespan-reporting = { workspace = true }
