[package]
name = "lun_semack"
description = "Sematic checker of lun."
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
lun_utils = { workspace = true }
lun_diag = { workspace = true }
lun_parser = { workspace = true }
