[package]
name = "l2_semack"
description = "Sematic checker of l2."
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
l2_utils = { workspace = true }
l2_diagnostic = { workspace = true }
l2_parser = { workspace = true }
