[package]
name = "lunc_token"
description = "Token related to tokens shared between lunc_lexer and lunc_parser."
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
lunc_utils = { workspace = true }

# other dependencies
